.github/workflows/code-style.yaml, .gitignore, graphein/construct_meshes.py, graphein/features/__init__.py, graphein/features/amino_acid.py, graphein/features/edges/distance.py, graphein/features/edges/intramolecular.py, graphein/features/sequence.py, graphein/features/utils.py, graphein/protein/config.py, graphein/protein/graphs.py, graphein/protein/resi_atoms.py, graphein/protein/utils.py, graphein/protein/visualisation.py, pyproject.toml
@a-r-j adding some code style continuous integration checks!
I'd recommend doing a squash merge rather than a direct merge commit. It'll keep the commit history a bit cleaner.
=> [INF] Introduce code style continuous integration checks

.gitignore, environment-dev.yml, graphein/diffusion.py, graphein/utils.py
@a-r-j this one is a bit "WIP" for the moment, I am hoping the code style checks (#29) get merged first. Then I'll add docstrings and tests for the diffusion matrices.
Also, I think I could use a bit of discussion on where to put what code. Please let me know if you think the code organization make sense thus far, or if they should be placed elsewhere.
=> [WIP] Add diffusion matrices

graphein/protein/edges/atomic.py, graphein/protein/edges/intramolecular.py, graphein/protein/graphs.py, graphein/protein/resi_atoms.py, graphein/protein/visualisation.py
Added in a 3D visualisation function for protein structure graphs. I think it's a nice feature to have - it plots nodes based on their xyz coords and supports a few colouring schemes.
The plots are pretty but there is evil lurking underneath. I think `colour_nodes` and, especially, `colour_edges` could use some improvement. The frozenset manipulations feel __dirty__.
=> Protein vis

graphein/protein/visualisation.py
Displays full graph with ability to rotate.
Helps resolve #15
=> Enable 3D visualisation with Plotly

graphein/protein/config.py, graphein/protein/edges/atomic.py, graphein/protein/resi_atoms.py, graphein/protein/visualisation.py
A collection of commits to cherry-pick or ignore.
=> Small tweaks and changes

graphein/protein/graphs.py
Fixes atom graph construction issue referenced in #41 #74 
Uncomments lines that prevented the atom graph dataframe from being accessed. Commented as part of a refactoring effort.
Manual testing
=> Bugfix for #41 and #74

graphein/protein/graphs.py, tests/protein/test_graphs.py
Implements #72
Implements multiprocessing of a list of PDB codes/paths to speed up data preparation.
Rough sanity check tests implemented. Would be great to hear any suggestions for additional tests :)
—
Created via [Raycast](https://www.raycast.com?ref=signatureGithub)
=> Add Multiprocessing to Protein Graph Construction

.github/workflows/build.yaml, graphein/grn/parse_regnetwork.py, graphein/ppi/visualisation.py, graphein/protein/edges/atomic.py, graphein/protein/edges/distance.py, graphein/protein/graphs.py, graphein/rna/visualisation.py, graphein/utils/utils.py, setup.py, tests/grn/test_graphs.py
Adds build testing for a matrix of PyTorch CPU & GPU versions
WIP
=> Package build

.requirements/base.in, setup.py
Fixes incorrect sklearn dependency #89
=> [Package] fix incorrect scikit-learn dependency (#89)

notebooks/interactive_plotly_example.ipynb
Adds an additional tutorial for interactive plotting in plotly.
=> [Tutorials] add interactive plotly example

.github/workflows/code-tests-docker.yaml, CHANGELOG.md, CONTRIBUTORS.md, Dockerfile, README.md, docker-compose.cpu.yml, docker-compose.yml
Fixes #69
I have added two docker compose files that enables users to build graphein locally on CPU and GPU (given Nvidia container toolkit is installed). This makes it easy to get the code up and running in a dev and usage env. As per #69 I haven't connected the container to a jupyter notebook because I prefer to mount the container in VS code. 
One important note is that graphein is not cloned and installed in the container but the local volume is mapped into the container. This means if the container fails you will still have any changes locally rather than in the contianer file system. 
To test the PR I also created `.github/workflows/code-tests-docker.yaml` that will run tests on the CPU built container for CICD. I tested these changes locally on GPU by:
```
docker-compose up -d …
```
=> added docker-compose and docker CICD for CPU and GPU

.requirements/base.in, CHANGELOG.md, Dockerfile, docker-compose.cpu.yml, docker-compose.yml, graphein/__init__.py, graphein/protein/graphs.py, setup.py, tests/protein/test_graphs.py
#98 #105 
* Improves filtering of PDB DF to remove altlocs & insertions more thoroughly.
* Pin versions of PyYaml and matplotlib to improve colab installation.
Adds example test for troublesome PDB with lots of insertions & altlocs.
=> [Bugfix] improve handling of insertions and altlocs #98

CHANGELOG.md, graphein/protein/features/nodes/amino_acid.py, graphein/protein/resi_atoms.py, tests/protein/nodes/features/test_amino_acid.py
N/A
Adds onehot encoding of Amino acid types as node features.
Includes example test and execution test.
=> Adds one-hot encoding of amino acids types as node feature

graphein/protein/utils.py, tests/protein/test_utils.py
* adds PDB save functions to `graphein.protein.utils`
* adds associated tests for new functions.
=> [WIP] add PDB and PyMol utilities [utils] 

CHANGELOG.md, graphein/protein/edges/distance.py, tests/protein/edges/test_distance.py
#115 
Adds sequence distance-based edges functions
Adds tests for the new function and peptide bonds.
* [] Update changelog
=> add sequence distance edges #115

CHANGELOG.md, graphein/__init__.py, graphein/testing/__init__.py, graphein/testing/utils.py, tests/protein/test_data/1lds.pdb, tests/testing/utils.py
#142
Adds utilities for testing equality of various graph components.
Added unit tests.
=> add graph equality funtions #142

CHANGELOG.md, graphein/protein/edges/distance.py
=> bugfix to distance edge func #146

CHANGELOG.md, graphein/protein/features/nodes/amino_acid.py, graphein/protein/resi_atoms.py, tests/protein/nodes/features/test_amino_acid.py
#145 
Adds hydrogen bond donor/acceptor featurisation options.
Tests pending.
=> Hydrogen bond acceptor/donor features

CHANGELOG.md, graphein/protein/graphs.py
=> prelim path support #269

CHANGELOG.md, graphein/ml/conversion.py
=> Minor patch `convert_nx_to_pyg` #280

CHANGELOG.md, README.md, docs/source/conf.py, graphein/__init__.py
=> Prep for 1.7.0 release

CHANGELOG.md, graphein/protein/graphs.py, graphein/protein/resi_atoms.py, graphein/protein/tensor/data.py, graphein/protein/tensor/io.py, graphein/protein/tensor/sequence.py, tests/protein/test_graphs.py
Improvements to insertions/non-standard residue handling in `graphein.protein.tensor` module.
=> Tensor fixes

CHANGELOG.md, docs/source/conf.py, graphein/__init__.py, graphein/ml/datasets/foldcomp_dataset.py
=> Change how foldcomp datasets are downloaded to specific location

docs/source/conf.py, graphein/__init__.py, setup.py
=> Bump version strings for 1.7.6 release

CHANGELOG.md, graphein/ml/datasets/pdb_data.py, graphein/protein/features/sequence/embeddings.py, graphein/protein/meshes.py, graphein/protein/tensor/io.py, graphein/protein/tensor/representation.py, graphein/protein/tensor/sequence.py, graphein/protein/utils.py, graphein/protein/visualisation.py
Set logging level down to `DEBUG` from `INFO` and `WARNING` at some places due to unnecessary terminal output there for functionality that is not used.
=> [cleanup] change logging levels to debug to declutter output
